version: '3.7'
services:
  postgres:
    image: postgres:11
    container_name: postgres_db
    ports:
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: "password"
    volumes:
      - $PWD/init.sql:/docker-entrypoint-initdb.d/init.sql
